# Generated by Django 3.2.9 on 2022-07-22 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Люкс', 'Люкс'), ('Полулюкс', 'Полулюкс'), ('Стандарт', 'Стандарт')], default='Стандарт', max_length=20, verbose_name='Тип комнаты')),
                ('number', models.CharField(max_length=50, verbose_name='Номер комнаты')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=15, verbose_name='ФИО клиента')),
                ('check_in', models.DateTimeField(verbose_name='Дата заезда')),
                ('check_out', models.DateTimeField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('Бронь', 'Бронь'), ('Проживает', 'Проживает'), ('Съехал', 'Съехал')], default='Бронь', max_length=20, verbose_name='Статус')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.rooms', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
