# Generated by Django 3.2.9 on 2022-07-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(max_length=100, verbose_name='ФИО клиента'),
        ),
    ]
